name = "GECaMBouchaudMezard"
uuid = "839a1018-e30d-4781-a685-a02c170cef92"
authors = ["Mattia Tarabolo"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
